FILE_LOCATION = r"C:\Data"
FILE_NAME = None
MULTI_FILE_NAME = []
FILE_NAME_INIT = "No File Chosen"
FILE_SUFFIX = None
FILE_NAME_SAVE = "_out"

COMPONENT_INDEX_DEFAULT = 0
QUANTITY_INDEX_DEFAULT = 3
N_ROWS_TO_PEAK_DEFAULT = 5
